title: Ffion Elisa
email: contact@ffionelisa.com
instagram_username: ffionelisa
markdown: kramdown
collections:
  work:
    output: false
  series:
    output: true
    permalink: /series/:name
  pages:
    output: true
    permalink: /:path
